Langos Charly/src/java/at/htlpinkafeld/langoscharly/gui/BestellungBean.java
package at.htlpinkafeld.langoscharly.gui;

import at.htlpinkafeld.langoscharly.pojo.Bestellposition;
import at.htlpinkafeld.langoscharly.pojo.Bestellung;
import at.htlpinkafeld.langoscharly.pojo.User;
import at.htlpinkafeld.langoscharly.service.LangosCharlyService;
import at.htlpinkafeld.langoscharly.utilities.MailClient;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;
import java.util.stream.Collectors;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;

/**
 *
 * @author DominikT
 */
public class BestellungBean implements BaseBean {

    private LangosCharlyService service;
    private LocalDate datum;
    private String ort;
    private int plz;
    private String adresse;
    private int anz;
    private List<Integer> menge = new LinkedList<>();
    private List<Integer> mengeCopy = new LinkedList<>();
    private Bestellung bestellung;
    private List<Bestellposition> bestellpositionen = new LinkedList<>();
    private boolean rendered = false;
    private Bestellposition bestellposition;
    private List<Bestellung> bestellungen = new LinkedList<>();
    private Map<String, Integer> confirmMap = new HashMap<>();

    public BestellungBean() {
    }

    public int getAnz() {
        return anz;
    }

    public void setAnz(int anz) {
        this.anz = anz;
        this.menge.add(this.anz);
        this.mengeCopy.add(this.anz);
    }

//    public int getMin() {
//        if (!this.confirmMap.isEmpty()) {
//            for (int i = 0, j = 0; i < this.service.getVerfuegbareLangos().size(); i++, j++) {
//                if (this.service.getVerfuegbareLangos().get(i).getName().equals(this.confirmMap.entrySet().stream().collect(Collectors.toList()).get(j).getKey())) {
//                    return this.confirmMap.entrySet().stream().collect(Collectors.toList()).get(j).getValue();
//                } else {
//                    j--;
//                }
//            }
//        }
//        return 0;
//    }
    @Override
    public LangosCharlyService getLangosCharlyService() {
        return service;
    }

    @Override
    public void setLangosCharlyService(LangosCharlyService service) {
        this.service = service;
    }

    public LocalDate getDatum() {
        return datum;
    }

    public void setDatum(LocalDate datum) {
        this.datum = datum;
    }

    public String getOrt() {
        return ort;
    }

    public void setOrt(String ort) {
        this.ort = ort;
    }

    public int getPlz() {
        return plz;
    }

    public void setPlz(int plz) {
        this.plz = plz;
    }

    public String getAdresse() {
        return adresse;
    }

    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    public List<Integer> getMenge() {
        return menge;
    }

    public void setMenge(List<Integer> menge) {
        this.menge = menge;
    }

    public List<Bestellung> getBestellungen() {
        try {
            this.bestellungen = this.service.getBestellungen();
            return this.bestellungen;
        } catch (Exception e) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Keine Daten zum anzeigen vorhanden"));
        }
        return null;
    }

    public void setBestellungen(List<Bestellung> bestellungen) {
        this.bestellungen = bestellungen;
    }

    public List<Bestellung> getBestellungenByCurrentUser() {
        return this.service.getBestellungenByUser(this.service.getCurrentUser()).stream().sorted((b1, b2) -> b2.getDatum().compareTo(b1.getDatum())).collect(Collectors.toList());
    }

    public LocalDate getMinDate() {
        return LocalDate.now().plusDays(3);
    }

    private void sendMail() {
        User user = this.service.getCurrentUser();

        if (user != null) {

            StringBuilder langosBuilder = new StringBuilder();

            langosBuilder.append("Lieferdatum: ").append(bestellung.getDatum().format(DateTimeFormatter.ofPattern("dd LLLL yyyy"))).append("\n");

            for (Bestellposition bp : getBestellpositionenByBestellID(bestellung.getBestellID())) {
                langosBuilder.append(this.service.getLangos(bp.getLangosID()).getName()).append(": \t").append(bp.getMenge()).append("\n");
            }

            String text = service.getInformation(5).getText();
            StringBuilder username = new StringBuilder();

            switch (user.getTyp()) {
                case PRIVAT:
                    username.append("Sehr geehrte/r ").append(user.getVorname()).append(" ").append(user.getNachname());
                    break;
                case FIRMA:
                    username.append("Sehr geehrte Firma ").append(user.getFirmenname());
                    break;
                case VEREIN:
                    username.append("Sehr geehrter Verein ").append(user.getFirmenname());
                    break;
            }

            text = text.replace("USERNAME", username.toString()).replace("DETAILS", langosBuilder.toString());

            MailClient.sendMail(user.getEmail(), "Anfragebestätigung", text);
            MailClient.sendMail("Neue Bestellanfrage", "Sehr geehrtes Admin-Team!\n\nEin neue Bestellung ist im System mit folgenden Datum: " + bestellung.getDatum().format(DateTimeFormatter.ofPattern("dd LLLL yyyy")) + ".\n\n[Diese Email wird automatisch generier]");
        }
    }

    public String bestellen() {
        try {
            bestellung = this.service.createBestellung(new Bestellung(this.service.getCurrentUser().getID(), this.datum, this.ort, this.plz, this.adresse));
            for (int i = 0; i < this.service.getVerfuegbareLangos().size(); i++) {
                if (this.menge.get(i) > 0) {
                    this.service.createBestellposition(new Bestellposition(bestellung.getBestellID(), this.service.getLangos().get(i).getID(), this.menge.get(i)));
                }
            }

            new Thread(() -> {
                try {
                    if (bestellung != null) {
                        sendMail();
                    }
                } catch (Exception e) {
                    Logger.getLogger(this.getClass()).fatal("Mail konnte nicht gesendet werden.");
                }
            }).start();

        } catch (Exception e) {
            if (bestellung != null) {
                this.service.deleteBestellung(bestellung);
            }
            Logger.getLogger(BestellungBean.class).log(Level.FATAL, "Erstellen der Bestellung nicht erfolgreich!", e);
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Ein Fehler ist aufgetreten", "Die Bestellung konnte nicht ausgeführt werden"));
            return null;
        }
        this.menge.clear();

        return "bestellUebersicht.xhtml?faces-redirect=true";

    }

    public Bestellposition getBestellposition() {
        return bestellposition;
    }

    public void setBestellposition(Bestellposition bestellposition) {
        this.bestellposition = bestellposition;
    }

    public Bestellung getBestellung() {
        return bestellung;
    }

    public List<Bestellposition> getBestellpositionen() {
        return this.bestellpositionen;
    }

    public boolean isRendered() {
        return rendered;
    }

    public void setBestellung(Bestellung bestellung) {
        this.bestellung = bestellung;
    }

    public void setBestellpositionen(List<Bestellposition> bestellpositionen) {
        this.bestellpositionen = bestellpositionen;
    }

    public void setRendered(boolean rendered) {
        this.rendered = rendered;
    }

    public void deleteBestellung(Bestellung b) {
        this.service.deleteBestellung(b);
    }

    public void deleteBestellungByAdmin(Bestellung b) {
        this.service.deleteBestellung(b);

        StringBuilder username = new StringBuilder();

        User user = this.service.getUser(this.bestellung.getUserID());

        switch (user.getTyp()) {
            case PRIVAT:
                username.append("Sehr geehrte/r ").append(user.getVorname()).append(" ").append(user.getNachname());
                break;
            case FIRMA:
                username.append("Sehr geehrte Firma ").append(user.getFirmenname());
                break;
            case VEREIN:
                username.append("Sehr geehrter Verein ").append(user.getFirmenname());
                break;
        }

        MailClient.sendMail(user.getEmail(), "Absage der Langos Bestellung", this.service.getInformation(10).getText().replace("AKTIVITÄT", "Bestellung").replace("USERNAME", username.toString()));
    }

    public List<Bestellposition> getBestellpositionenByBestellID(int id) {
        this.bestellpositionen = this.service.getBestellpositionenByBestellID(id);

        return this.bestellpositionen;
    }

    public void updateBestellung(Bestellung bestellung) {
        service.updateBestellung(bestellung);
    }

    public void updateBestellPosition(Bestellposition bestellposition) {
        this.service.updateBestellposition(bestellposition);
    }

    public String addUserLangos() {
        reset();

        for (int i = 0; i < this.service.getVerfuegbareLangos().size(); i++) {
            if (this.mengeCopy.get(i) > 0) {
                this.confirmMap.put(this.service.getVerfuegbareLangos().get(i).getName(), this.mengeCopy.get(i));
            }
        }

        this.mengeCopy.clear();

        return "anschrift.xhtml?faces-redirect=true";
    }

//    public int getPlaceholder() {
////        if (this.confirmMap != null) {
////            for (Entry<String, Integer> entry : this.confirmMap.entrySet()) {

Langos Charly/src/java/at/htlpinkafeld/langoscharly/gui/LangosBean.java
package at.htlpinkafeld.langoscharly.gui;

import at.htlpinkafeld.langoscharly.dao.factory.DAOFactory;
import at.htlpinkafeld.langoscharly.pojo.Langos;
import at.htlpinkafeld.langoscharly.service.LangosCharlyService;
import at.htlpinkafeld.langoscharly.utilities.UserException;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import org.apache.log4j.Logger;
import org.primefaces.event.FileUploadEvent;

/**
 *
 * @author Kolar
 */
public class LangosBean implements BaseBean {

    private LangosCharlyService service;

    private String name, beschreibung, allergene, bemerkung;
    private int mindestbestand;
    private boolean verfuegbar;
    private InputStream bild;

    public LangosBean() {
    }

    @Override
    public LangosCharlyService getLangosCharlyService() {
        return service;
    }

    @Override
    public void setLangosCharlyService(LangosCharlyService service) {
        this.service = service;
    }

    public List<Langos> getLangos() {
        return DAOFactory.getInstance().readAllLangos();
    }

    public String saveLangos(Langos langos) {
        service.updateLangos(langos);
        return null;
    }

    public String deleteLangos(Langos langos) {
        service.deleteLangos(langos);

        return null;
    }

    public void updateLangos(Langos langos) {
        if (bild != null) {
            service.updateImage(langos, bild);
        }
        service.updateLangos(langos);
    }

    public LangosCharlyService getService() {
        return service;
    }

    public void setService(LangosCharlyService service) {
        this.service = service;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBeschreibung() {
        return beschreibung;
    }

    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }

    public String getAllergene() {
        return allergene;
    }

    public void setAllergene(String allergene) {
        this.allergene = allergene;
    }

    public InputStream getBild() {
        return bild;
    }

    public void setBild(InputStream bild) {
        this.bild = bild;
    }

    public String getBemerkung() {
        return bemerkung;
    }

    public void setBemerkung(String bemerkung) {
        this.bemerkung = bemerkung;
    }

    public int getMindestbestand() {
        return mindestbestand;
    }

    public void setMindestbestand(int mindestbestand) {
        this.mindestbestand = mindestbestand;
    }

    public boolean isVerfuegbar() {
        return verfuegbar;
    }

    public void setVerfuegbar(boolean verfuegbar) {
        this.verfuegbar = verfuegbar;
    }

    public void fileUpload(FileUploadEvent event) {
        try {
            bild = event.getFile().getInputstream();
            
            FacesContext context = FacesContext.getCurrentInstance();
            context.addMessage("Bild hochgeladen", new FacesMessage("Erfolgreich", "Bild wurde erfolgreich hochgeladen"));
        } catch (IOException e) {
            Logger.getLogger(LangosBean.class).fatal("Bild nicht möglich hochzuladen: " + e.getMessage(), e);
        }

    }
    
    public void cancel(){
        bild = null;
    }

    public String neuesLangos() {

        Langos langos = new Langos(name, beschreibung, allergene, mindestbestand, verfuegbar, bemerkung);

        try {
            service.createLangos(langos);

            name = null;
            beschreibung = null;
            allergene = null;
            bild = null;
            mindestbestand = 0;
            verfuegbar = false;
            bemerkung = null;

            return "langos.xhtml?faces-redirect=true";
        } catch (UserException ex) {
            FacesContext context = FacesContext.getCurrentInstance();
            context.addMessage(null, new FacesMessage(ex.getSeverity(), "Ein Problem ist Aufgetreten", ""));

        }

        return null;

    }

    public List<Langos> getVerfuegbareLangos() {
        return this.service.getVerfuegbareLangos();
    }

    public String getNameofLangosByID(int id) {
        return this.service.getLangos(id).getName();
    }

}

Langos Charly/web/bestellen/anschrift.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template/template.xhtml">

    <ui:define name="content">
        <div class="ui-g">
            <div class="ui-g-12">
                <div class="card centerText">
                    <h1 class="lightBlack">Anschrift</h1>
                    <h:form >
                        
                        <p:growl id="growl" sticky="false" showDetail="true" life="10000" />

                        <style type="text/css">
                            body .ui-steps .ui-steps-item {
                                width: 33%;
                            }
                        </style>

                        <p:steps activeIndex="1" styleClass="custom" readonly="false" >
                            <p:menuitem value="Produkte" url="products.xhtml?faces-redirect=true"/>
                            <p:menuitem value="Anschrift" url="anschrift.xhtml?faces-redirect=true"/>
                            <p:menuitem value="Bestätigen" url="bestaetigen.xhtml?faces-redirect=true"/>
                        </p:steps>

                        <br/>

                        <p:panelGrid columns="1" styleClass="noBorders" >
                        <h:panelGrid columns="2" >
                            <p:outputLabel for="datum" value="Lieferdatum: " />
                            <p:calendar id="datum" value="#{bestellungBean.datum}" mindate="#{bestellungBean.minDate}" locale="de" navigator="true" pattern="dd.MM.yyyy" converter="dateConvId" required="true" />
                            <p:outputLabel for="ort" value="Ort: " style="float: left" />
                            <p:inputText id="ort" value="#{bestellungBean.ort}" required="true" requiredMessage="Bitte Ort Eingeben." />
                            <p:outputLabel for="plz" value="PLZ: " style="float: left" />
                            <p:inputText type="number" id="plz" value="#{bestellungBean.plz}" required="true" validator="PLZValId" />
                            <p:outputLabel for="adresse" value="Adresse: " style="float: left" />
                            <p:inputText id="adresse" value="#{bestellungBean.adresse}" required="true" requiredMessage="Bitte Adresse Eingeben." />
                        </h:panelGrid>
                        </p:panelGrid>
                            
                        <br/>

                        <p:commandButton action="bestaetigen.xhtml?faces-redirect=true" value="Weiter" />

                    </h:form>
                </div>
            </div>
        </div>   
    </ui:define>

</ui:composition>

Langos Charly/web/bestellen/bestellUebersicht.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template/template.xhtml">

    <ui:define name="content">
        <div class="ui-g">
            <div class="ui-g-12">
                <div class="card centerText">
                    <h1 class="lightBlack">Bestellübersicht</h1>

                    <h:form id="form">

                        <p:growl id="growl" sticky="false" showDetail="true" life="10000" />

                        <p:dataTable value="#{bestellungBean.bestellungenByCurrentUser}" editable="true" var="b">

                            <p:ajax event="rowEdit" listener="#{bestellungBean.updateBestellung(b)}" />

                            <f:facet name="header">
                                Bestellungen
                            </f:facet>

                            <p:column headerText="PLZ" sortBy="#{bestellung.plz}">
                                <p:cellEditor>
                                    <f:facet name="output">
                                        <h:outputText value="#{b.plz}" />
                                    </f:facet>
                                    <f:facet name="input">
                                        <p:inputText value="#{b.plz}" style="width:100%"/>
                                    </f:facet>
                                </p:cellEditor>
                            </p:column>

                            <p:column headerText="Ort" sortBy="#{bestellung.ort}">
                                <p:cellEditor>
                                    <f:facet name="output">
                                        <h:outputText value="#{b.ort}" />
                                    </f:facet>
                                    <f:facet name="input">
                                        <p:inputText value="#{b.ort}" style="width:100%"/>
                                    </f:facet>
                                </p:cellEditor>
                            </p:column>

                            <p:column headerText="Adresse" sortBy="#{bestellung.adresse}">
                                <p:cellEditor>
                                    <f:facet name="output">
                                        <h:outputText value="#{b.adresse}" />
                                    </f:facet>
                                    <f:facet name="input">
                                        <p:inputText value="#{b.adresse}" style="width:100%"/>
                                    </f:facet>
                                </p:cellEditor>
                            </p:column>

                            <p:column headerText="Datum" sortBy="#{bestellung.datum}">
                                <h:outputText value="#{b.datum}" converter="dateConvId" />
                            </p:column>

                            <p:column style="width:35px">
                                <p:rowEditor rendered="#{!b.bestaetigt}"/>
                            </p:column>

                            <p:column style="width:35px">
                                <p:commandLink class="fa fa-trash-o" action="#{bestellungBean.deleteBestellung(b)}"  rendered="#{!b.bestaetigt}" update="@form">
                                    <p:confirm header="Bestätigung" message="Sind Sie sicher das Sie die Bestellung löschen wollen?" />
                                </p:commandLink>

                                <p:confirmDialog global="true" showEffect="fade" hideEffect="fade" >
                                    <p:commandButton value="Löschen" type="button" styleClass="ui-confirmdialog-yes" style="margin-left: 30%"/>
                                    <p:commandButton value="Abbrechen" type="button" styleClass="ui-confirmdialog-no"/>
                                </p:confirmDialog>
                            </p:column>

                            <p:column style="width:32px;text-align: center">
                                <p:commandButton update=":form" oncomplete="PF('BestellungDialog').show()" icon="fa fa-search" title="Bestellung anzeigen">
                                    <f:setPropertyActionListener value="#{b}" target="#{bestellungBean.bestellung}" />
                                </p:commandButton>
                            </p:column>
                        </p:dataTable>

                        <p:dialog header="Bestellung" widgetVar="BestellungDialog" minWidth="350" width="500" style="width: 60% !important; left: 25% !important; top: 40% !important" modal="true" showEffect="fade" hideEffect="explode" resizable="true">
                            <p:outputPanel id="dialog" style="text-align:center;">

                                <p:dataTable id="bestellungTable" value="#{bestellungBean.getBestellpositionenByBestellID(bestellungBean.bestellung.bestellID)}" var="bestellposition">

                                    <p:column headerText="Langos" >
                                        <h:outputText value="#{langosBean.getNameofLangosByID(bestellposition.langosID)}" />
                                    </p:column>

                                    <p:column headerText="Menge" >   
                                        <h:outputText value="#{bestellposition.menge}" />
                                    </p:column>

                                </p:dataTable>

                            </p:outputPanel>
                        </p:dialog>








                    </h:form>
                </div>
            </div>
        </div>

    </ui:define>

</ui:composition>

Langos Charly/web/bestellen/langosBestellen.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template/template.xhtml">

    <ui:define name="content">
        <div class="ui-g">
            <div class="ui-g-12">
                <div class="card centerText">
                    <h1 class="lightBlack">Langos Bestellen</h1>
                    <h:form id="bestellung" >

                        <p:growl id="growl" sticky="false" showDetail="true" life="10000" />

                        <h:panelGrid columns="2" >
                            <h:panelGrid columns="2" >
                                <p:outputLabel for="datum" value="Lieferdatum: " style="float: left" />
                                <p:calendar id="datum" value="#{bestellungBean.datum}" locale="de" navigator="true" pattern="dd.MM.yyyy" converter="dateConvId"/>
                                <p:outputLabel for="ort" value="Ort: " style="float: left" />
                                <p:inputText id="ort" value="#{bestellungBean.ort}" />
                                <p:outputLabel for="plz" value="PLZ: " style="float: left" />
                                <p:inputText type="number" id="plz" value="#{bestellungBean.plz}" />
                                <p:outputLabel for="adresse" value="Adresse: " style="float: left" />
                                <p:inputText id="adresse" value="#{bestellungBean.adresse}" />

                            </h:panelGrid>

                            <p:dataTable var="langos" value="#{langosBean.verfuegbareLangos}">
                                <p:column headerText="Langos">
                                    <h:outputText value="#{langos.name}" />
                                </p:column>

                                <p:column headerText="Menge">
                                    <p:spinner value="#{bestellungBean.anz}" min="0" stepFactor="50"/>
                                </p:column>
                            </p:dataTable>

                            <br/>
                            <br/>
                            <p:commandButton id="bestellen" action="#{bestellungBean.bestellen}" value="Bestellen" />
                            <br/>
                            <p:commandButton id="bestellübersicht" action="bestellUebersicht.xhtml?faces-redirect=true" value="Bestellübersicht" immediate="true" />
                        </h:panelGrid>
                    </h:form>
                </div>
            </div>
        </div>   
    </ui:define>

</ui:composition>

Langos Charly/web/bestellen/products.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template/template.xhtml">

    <ui:define name="content">
        <div class="ui-g">
            <div class="ui-g-12">
                <div class="card centerText">
                    <h1 class="lightBlack">Produkte</h1>
                    <h:form >

                        <p:growl id="growl" sticky="false" showDetail="true" life="10000" />

                        <style type="text/css">
                            body .ui-steps .ui-steps-item {
                                width: 33%;
                            }
                        </style>

                        <p:steps activeIndex="0" styleClass="custom" readonly="false" >
                            <p:menuitem value="Produkte" url="products.xhtml?faces-redirect=true"/>
                            <p:menuitem value="Anschrift" url="anschrift.xhtml?faces-redirect=true"/>
                            <p:menuitem value="Bestätigen" url="bestaetigen.xhtml?faces-redirect=true"/>
                        </p:steps>

                        <br/>

                        <p:dataTable tableStyle="width: auto" rowIndexVar="idx" id="products" var="langos" value="#{langosBean.verfuegbareLangos}">
                            <p:column headerText="Produkte">
                                <h:outputText id="showImage" value="#{langos.name}" />

                                <p:tooltip id="img" for="showImage" showEffect="blind" hideEffect="explode" showEvent="mouseover">
                                    <p:graphicImage value="#{imageBean.image}" alt="Kein Bild verfügbar">
                                        <f:param name="langosID" value="#{langos.ID}"/>
                                    </p:graphicImage>

                                    <br/>

                                    <p:outputLabel style="width: 100%; text-align: center;" value="Allergene: #{langos.allergene}" />
                                </p:tooltip>
                            </p:column>

                            <p:column headerText="Menge">
                                <p:spinner min="0" value="#{bestellungBean.anz}"  stepFactor="50" />
                            </p:column>
                        </p:dataTable>

                        <br/>

                        <p:commandButton action="#{bestellungBean.addUserLangos}" value="Weiter" />

                    </h:form>
                </div>
            </div>
        </div>   
    </ui:define>

</ui:composition>