Langos Charly/src/java/at/htlpinkafeld/langoscharly/gui/StatistikBean.java
package at.htlpinkafeld.langoscharly.gui;

import at.htlpinkafeld.langoscharly.pojo.Bestellposition;
import at.htlpinkafeld.langoscharly.pojo.Bestellung;
import at.htlpinkafeld.langoscharly.pojo.Fest;
import at.htlpinkafeld.langoscharly.pojo.FestLangos;
import at.htlpinkafeld.langoscharly.pojo.FestSpeisen;
import at.htlpinkafeld.langoscharly.service.LangosCharlyService;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import org.primefaces.model.chart.PieChartModel;

/**
 *
 * @author Kolar
 */
public class StatistikBean implements BaseBean {

    private LangosCharlyService service;

    private boolean typ = false; //Bestellung = true; Fest = false
    private boolean selectAll = false;
    private List<Fest> selectedFeste;
    private List<Bestellung> selectedBestellungen;

    public StatistikBean() {
    }

    @Override
    public LangosCharlyService getLangosCharlyService() {
        return service;
    }

    @Override
    public void setLangosCharlyService(LangosCharlyService service) {
        this.service = service;
    }

    public boolean isTyp() {
        return typ;
    }

    public void setTyp(boolean typ) {
        this.typ = typ;
        selectAll = false;
        selectedBestellungen = null;
        selectedFeste = null;
    }

    public List<Fest> getFeste() {
        try {
            List<Fest> helpList = new LinkedList<>();
            for(Fest fest : service.getFeste())
                if(fest.isAbgeschlossen()){
                    helpList.add(fest);
                }
            return helpList;
        } catch (Exception ex) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Keine Daten zum anzeigen vorhanden"));
        }
        return null;
    }

    public List<Bestellung> getBestellungen() {
        try {
            List<Bestellung> helpList = new LinkedList<>();
            for(Bestellung bestellung : service.getBestellungen())
                if(bestellung.isBestaetigt()){
                    helpList.add(bestellung);
                }
            return helpList;
        } catch (Exception ex) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Keine Daten zum anzeigen vorhanden"));
        }
        return null;
    }

    public boolean isSelectAll() {
        return selectAll;
    }

    public void setSelectAll(boolean selectAll) {
        this.selectAll = selectAll;
    }

    public void onSelectAll() {
        if (selectAll) {
            if (typ) {
                selectedBestellungen = getBestellungen();
            } else {
                selectedFeste = getFeste();
            }
        } else {
            selectedFeste = null;
            selectedBestellungen = null;
        }
    }

    public List<Fest> getSelectedFeste() {
        return selectedFeste;
    }

    public void setSelectedFeste(List<Fest> selectedFeste) {
        this.selectedFeste = selectedFeste;
    }

    public List<Bestellung> getSelectedBestellungen() {
        return selectedBestellungen;
    }

    public void setSelectedBestellungen(List<Bestellung> selectedBestellungen) {
        this.selectedBestellungen = selectedBestellungen;
    }

    public PieChartModel getModel() {
        PieChartModel model = new PieChartModel();
        Map<String, Number> map = new HashMap<>();

        if (typ) {

            if (selectedBestellungen == null) {
                return new PieChartModel();
            }

            int idx = 0;
            for (Bestellung b : selectedBestellungen) {
                if (idx == 0) {
                    map = getMapOutOfBestellung(b);
                    idx++;
                } else {
                    map = concatMaps(map, getMapOutOfBestellung(b));
                }
            }
            model.setData(map);

        } else {

            if (selectedFeste == null) {
                return new PieChartModel();
            }

            int idx = 0;
            for (Fest f : selectedFeste) {
                if (idx == 0) {
                    map = getMapOutOfFest(f);
                    idx++;
                } else {
                    map = concatMaps(map, getMapOutOfFest(f));
                }
            }
            model.setData(map);

        }

        model.setLegendPosition("w");
        model.setShowDataLabels(true);
        model.setDiameter(150);
        model.setShadow(false);
        model.setLegendCols(3);

        return model;
    }

    private Map<String, Number> getMapOutOfBestellung(Bestellung b) {
        Map<String, Number> map = new HashMap<>();

        for (Bestellposition bp : service.getBestellpositionenByBestellID(b.getID())) {
            map.put(service.getLangos(bp.getLangosID()).getName(), (Number) (bp.getMenge()));
        }

        return map;
    }

    private Map<String, Number> getMapOutOfFest(Fest f) {
        Map<String, Number> map = new HashMap<>();

        for (FestSpeisen speise : service.getFestSpeisenByFestID(f.getID())) {
            map.put(service.getHauptspeise(speise.getHauptspeiseID()).getName(), speise.getMenge());
        }

        for (FestLangos langos : service.getFestLangosByFestID(f.getID())) {
            map.put(service.getLangos(langos.getLangosID()).getName(), (Number) (langos.getMenge()));
        }

        return map;
    }

    private Map<String, Number> concatMaps(Map<String, Number> m1, Map<String, Number> m2) {
        Map<String, Number> map = new HashMap<>(m1);

        m2.forEach((key, value) -> map.merge(key, value, (v1, v2) -> (Number) (v1.intValue() + v2.intValue())));

        return map;
    }

}

Langos Charly/web/statistik/statistik.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template/template.xhtml"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <ui:define name="content">
        <div class="ui-g">
            <div class="ui-g-12">
                <div class="card centerText">
                    <h1 class="lightBlack">Statistik</h1>

                    <h:form>

                        <p:panelGrid id="all" columns="2" style="width: 100%" class="noBorders">

                            <p:panelGrid columns="1" style="width: 100%" class="noBorders">


                                <p:outputLabel for="typ" value="Welche Statistik wollen Sie Ausgeben?" />
                                <p:selectOneRadio id="typ" value="#{statistikBean.typ}" style="text-align: start; margin: 0 auto">
                                    <f:selectItem itemLabel="Fest" itemValue="false"/>
                                    <f:selectItem itemLabel="Bestellung" itemValue="true"/>
                                    <p:ajax update="@form" />
                                </p:selectOneRadio>

                                <c:choose>

                                    <c:when test="#{statistikBean.typ}">
                                        <p:selectBooleanCheckbox itemLabel="Alle Bestllungen auswerten?" value="#{statistikBean.selectAll}">
                                            <f:ajax listener="#{statistikBean.onSelectAll()}" render="all"/>
                                        </p:selectBooleanCheckbox>

                                        <p:outputLabel value="Welche Bestellung wollen Sie Auswerten?" />
                                        <p:selectManyMenu id="items" value="#{statistikBean.selectedBestellungen}" filter="true" filterMatchMode="contains" showCheckbox="true" style="margin: 0 auto; text-align: left;" converter="bestellenConverterID">
                                            <f:selectItems value="#{statistikBean.bestellungen}" var="b" itemLabel="#{b.ort}"/>
                                            <p:ajax update="@form" />
                                        </p:selectManyMenu>

                                    </c:when>
                                    <c:otherwise>
                                        <p:selectBooleanCheckbox itemLabel="Alle Fest auswerten?" value="#{statistikBean.selectAll}">
                                            <f:ajax listener="#{statistikBean.onSelectAll()}" render="all"/>
                                        </p:selectBooleanCheckbox>

                                        <p:outputLabel value="Welche Feste wollen Sie Auswerten?" />
                                        <p:selectManyMenu id="items" value="#{statistikBean.selectedFeste}" filter="true" filterMatchMode="contains" showCheckbox="true" style="margin: 0 auto; text-align: left;" converter="festConverterID">
                                            <f:selectItems value="#{statistikBean.feste}" var="f" itemLabel="#{f.festName}"/>
                                            <p:ajax update="@form" />
                                        </p:selectManyMenu>

                                    </c:otherwise>

                                </c:choose>

                            </p:panelGrid>


                            <p:panelGrid columns="1" style="width: 100%" class="noBorders">

                                <p:chart type="pie" model="#{statistikBean.model}" style="width:700px; height:300px; text-align: left"/>

                            </p:panelGrid>




                        </p:panelGrid>






                    </h:form>
                </div>
            </div>
        </div>

    </ui:define>

</ui:composition>