Langos Charly/src/java/at/htlpinkafeld/langoscharly/gui/UserBean.java
package at.htlpinkafeld.langoscharly.gui;

import at.htlpinkafeld.langoscharly.pojo.Rolle;
import at.htlpinkafeld.langoscharly.pojo.User;
import at.htlpinkafeld.langoscharly.pojo.enums.Typ;
import at.htlpinkafeld.langoscharly.service.LangosCharlyService;
import at.htlpinkafeld.langoscharly.utilities.MailClient;
import at.htlpinkafeld.langoscharly.utilities.PasswortEncryption;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.security.spec.InvalidKeySpecException;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.event.PhaseId;
import javax.imageio.ImageIO;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

/**
 *
 * @author Kolar
 */
public class UserBean implements BaseBean {

    private LangosCharlyService service;
    private InputStream bild;
    private int userID;
    private String firmenname;
    private Typ typ = Typ.FIRMA;
    private String vorname, nachname;
    private String email;
    private String passwort;
    private String telefonnummer;
    private String adresse;
    private int plz;
    private String ort;
    private Rolle rolle;
    private User changeUser;
    private int rollenID;
    private String neuesPasswort;

    private List<Rolle> rollen;
    private final String cookieUserID = "cUserID";
    private final String cookiePw = "cPw";
    private final int cookieDuration = 2628000; // 1 Monat
    private final String cookiePath = "/";
    private final boolean cookieHttpOnly = true;

    public UserBean() {
    }

    @PostConstruct
    public void init() {
        typ = Typ.FIRMA;

        new Thread(() -> {
            service.preLoad();
        }).start();
        
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = ((HttpServletRequest) (context.getExternalContext().getRequest()));
        HttpServletResponse response = ((HttpServletResponse) (context.getExternalContext().getResponse()));

        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        if (request.getParameter("JSESSIONID") != null) {
            Cookie userCookie = new Cookie("JSESSIONID", request.getParameter("JSESSIONID"));
            response.addCookie(userCookie);
        } else {
            String sessionId = session.getId();
            Cookie userCookie = new Cookie("JSESSIONID", sessionId);
            response.addCookie(userCookie);
        }

        
        Cookie[] cookiesArr = request.getCookies();
        if (cookiesArr != null && cookiesArr.length > 0) {
            for (Cookie cookie : cookiesArr) {
                String cName = cookie.getName();
                String cValue = cookie.getValue();

                if (cName.equals(cookieUserID)) {
                    userID = Integer.valueOf(cValue);
                } else if (cName.equals(cookiePw)) {
                    passwort = cValue;
                }
            }
        }
        if (userID > -1 && passwort != null && passwort.length() > 0) {

            try {

                setCookies(userID, passwort);

            } catch (Exception ex) {
            }

            try {
                passwort = passwort.replace("+", " ");
                login(this.service.getUser(userID), passwort);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(UserBean.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        } else {
            passwort = null;
            userID = -1;
        }
    }

    public boolean isFirma() {
        return typ.equals(Typ.FIRMA);
    }

    public boolean isVerein() {
        return typ.equals(Typ.VEREIN);
    }

    public String getNeuesPasswort() {
        return neuesPasswort;
    }

    public void setNeuesPasswort(String neuesPasswort) {
        this.neuesPasswort = neuesPasswort;
    }

    public LangosCharlyService getService() {
        return service;
    }

    public void setService(LangosCharlyService service) {
        this.service = service;
    }

    public void setUserID(int userID) {
        this.userID = userID;
    }

    public InputStream getBild() {
        return bild;
    }

    public void setBild(InputStream bild) {
        this.bild = bild;
    }

    public String getFirmenname() {
        return firmenname;
    }

    public void setFirmenname(String Firmenname) {
        this.firmenname = Firmenname;
    }

    public Typ getTyp() throws IOException {
        return typ;
    }

    public void setTyp(Typ typ) {
        this.typ = typ;
    }

    public String getVorname() {
        return vorname;
    }

    public void setVorname(String vorname) {
        this.vorname = vorname;
    }

    public String getNachname() {
        return nachname;
    }

    public void setNachname(String nachname) {
        this.nachname = nachname;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPasswort() {
        return passwort;
    }

    public void setPasswort(String passwort) {
        this.passwort = passwort;
    }

    public String getTelefonnummer() {
        return telefonnummer;
    }

    public void setTelefonnummer(String telefonnummer) {
        this.telefonnummer = telefonnummer;
    }

    public String getAdresse() {
        return adresse;
    }

    public void setAdresse(String Adresse) {
        this.adresse = Adresse;
    }

    public int getPlz() {
        return plz;
    }

    public void setPlz(int plz) {
        this.plz = plz;
    }

    public String getOrt() {
        return ort;
    }

    public void setOrt(String ort) {
        this.ort = ort;
    }

    public int getUserID() {
        return userID;
    }

    public Rolle getRolle() {
        return rolle;
    }

    public void setRollenID(int rollenID) {
        this.rollenID = rollenID;
    }

    public int getRollenID() {
        return rollenID;
    }

    public List<Rolle> getRollen() {
        rollen = service.getRollen();
        return rollen;
    }

    public String getName(User user) {
        return service.getName(user);
    }

    public String getName(int id) {
        return getName(this.service.getUser(id));
    }

    public StreamedContent getImage() throws IOException {
        FacesContext context = FacesContext.getCurrentInstance();

        if (context.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
            return new DefaultStreamedContent();
        } else {

            return new DefaultStreamedContent(this.service.getCurrentUser().getBild(), "image/jpeg");
        }
    }

    public User getCurrentUser() {
        return this.service.getCurrentUser();
    }

    public boolean isPrivat() {
        if (service.getCurrentUser() != null) {
            return service.getCurrentUser().getTyp().equals(Typ.PRIVAT);
        }
        return false;
    }

    public boolean isDefaultImage() {
        try {
            if (service.getCurrentUser().getBild() != null) {
                return false;
            }
        } catch (Exception ex) {
        }

        return true;
    }

    public void fileUpload(FileUploadEvent event) {
        try {
            bild = event.getFile().getInputstream();

            BufferedImage sourceImage = ImageIO.read(bild);
            Image thumbnail = sourceImage.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
            BufferedImage bufferedThumbnail = new BufferedImage(thumbnail.getWidth(null),
                    thumbnail.getHeight(null),
                    BufferedImage.TYPE_INT_RGB);
            bufferedThumbnail.getGraphics().drawImage(thumbnail, 0, 0, null);
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            ImageIO.write(bufferedThumbnail, "jpeg", baos);
            bild = new ByteArrayInputStream(baos.toByteArray());

            FacesContext context = FacesContext.getCurrentInstance();
            context.addMessage(null, new FacesMessage("Erfolgreich", "Bild wurde erfolgreich hochgeladen"));

            this.service.updateImage(this.service.getCurrentUser(), bild);

        } catch (IOException e) {
            Logger.getLogger(UserBean.class).fatal("Bild nicht möglich hochzuladen: " + e.getMessage(), e);
        }
    }

    public void changePassword() {
        User user = service.getCurrentUser();
        user.setPasswort(passwort);
        this.service.updateUser(user);
    }

    public String register() throws IOException {

        if (typ.equals(Typ.PRIVAT)) {
            firmenname = Typ.PRIVAT.getName();
        }

        byte[] salt = null;
        byte[] hashedPasswort = null;
        try {
            salt = PasswortEncryption.salt();
            hashedPasswort = PasswortEncryption.hash(passwort, salt);

        } catch (InvalidKeySpecException | NoSuchAlgorithmException ex) {
            Logger.getLogger(UserBean.class
            ).fatal("User konnte nicht erstellt werden");
            System.out.println(ex.toString());
            throw new RuntimeException("User konnte nicht erstellt werden");
        }

Langos Charly/web/unternehmen/datenschutzerklaerung.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template/template.xhtml">

    <ui:define name="content">
        <div class="ui-g">
            <div class="ui-g-12">
                <div class="card centerText">
                    <h1 class="lightBlack">Datenschutzerklärung</h1>

                    <p>Der Schutz Ihrer persönlichen Daten ist uns ein besonderes Anliegen. Wir verarbeiten Ihre Daten daher ausschließlich auf Grundlage der gesetzlichen Bestimmungen (DSGVO, TKG 2003). In diesen Datenschutzinformationen informieren wir Sie über die wichtigsten Aspekte der Datenverarbeitung im Rahmen unserer Website. </p>

                    <h3 class="lightBlack">Kontakt mit uns</h3>

                    <p>Wenn Sie per Formular auf der Website oder per E-Mail Kontakt mit uns aufnehmen, werden Ihre angegebenen Daten zwecks Bearbeitung der Anfrage und für den Fall von Anschlussfragen bei uns gespeichert. Diese Daten geben wir nicht ohne Ihre Einwilligung weiter. </p>

                    <h3 class="lightBlack">Datenspeicherung</h3>

                    <p>Wir weisen darauf hin, dass zum Zweck des einfacheren Einkaufsvorganges und zur späteren Vertragsabwicklung Persöhnliche Daten gespeichert werden, wie z.B. Ihr Name, Anschrift und die Produkte und dsesen Menge. </p>

                    <h3 class="lightBlack">Cookies</h3>

                    <p>Unsere Website verwendet so genannte Cookies. Dabei handelt es sich um kleine Textdateien, die mit Hilfe des Browsers auf Ihrem Endgerät abgelegt werden. Sie richten keinen Schaden an.

                        Wenn Sie dies nicht wünschen, so können Sie Ihren Browser so einrichten, dass er Sie über das Setzen von Cookies informiert und Sie dies nur im Einzelfall erlauben.

                        Bei der Deaktivierung von Cookies kann die Funktionalität unserer Website eingeschränkt sein.</p>

                    <h3 class="lightBlack">Disclaimer</h3>

                    <p>Der genannte Betreiber ist bemüht, richtige und vollständige Informationen auf dieser Website bereitzustellen, übernimmt aber keinerlei Verantwortung, Garantien oder Haftung dafür, dass die durch diese Website bereitgestellten Informationen, einschließlich jeglicher Datenbankeinträge, richtig, vollständig oder aktuell sind. 

                        Der Betreiber behält sich das Recht vor, jederzeit und ohne Vorankündigung die Informationen auf dieser Website zu ändern und verpflichtet sich auch nicht, die enthaltenen Informationen zu aktualisieren. Die Hypertext-Links sind ausschließlich als Vereinfachung für die Benutzer gedacht und die Aufnahme eines beliebigen Links bedeutet keine Unterstützung oder Empfehlung der verlinkten Information durch den Betreiber und spiegelt nicht die Meinung des Betreibers wieder. Der Betreiber ist in keiner Weise verantwortlich für die Inhalte auf irgendeiner verlinkten Website oder irgendeinem Link in einer verlinkten Website. 

                        In keinem Fall kann der Betreiber für Schäden irgendeiner Art haftbar gemacht werden, die sich aus der Nutzung oder den Inhalten oder der Verfügbarkeit dieser Website, oder den Dokumenten, Diensten und Informationen auf dieser Website ergeben könnten. Dabei ist es gleichgültig, ob der Schaden direkter, indirekter oder finanzieller Natur ist, oder ein Folgeschaden oder sonstiger Schaden ist, der sich aus Datenverlust, Nutzungsausfall oder sonstigen Gründen aller Art ergeben könnte. </p>

                    <h3 class="lightBlack">Ihre Rechte</h3>

                    <p> Ihnen stehen bezüglich Ihrer bei uns gespeicherten Daten grundsätzlich die Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit, Widerruf und Widerspruch zu. Wenn Sie glauben, dass die Verarbeitung Ihrer Daten gegen das Datenschutzrecht verstößt oder Ihre datenschutzrechtlichen Ansprüche sonst in einer Weise verletzt worden sind, können Sie sich bei der uns [E-Mail-Adresse abgeben] oder der Datenschutzbehörde beschweren. </p>


                    <br/>
                    <h3 class="lightBlack">Sie erreichen uns unter folgenden Kontaktdaten:</h3>

                    <p><pre>Langos Charly:
E-Mail: <a href="mailto:office@langos-charly.at">office@langos-charly.at</a>
Tel:    +43 676 925 88 03       
 +43 664 414 3216 </pre></p>
                </div>

            </div>
        </div>

    </ui:define>

</ui:composition>

Langos Charly/web/unternehmen/logout.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/WEB-INF/template/template.xhtml"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

    <ui:define name="content">
        <div class="ui-g">
            <div class="ui-g-12">
                <div class="card centerText">
                    <h:form>
                        
                        <p:growl id="growl" sticky="false" showDetail="true" life="10000" />

                        <h1 class="lightBlack">Logout</h1>
                        <p class="lightBlack">Sind Sie sicher das Sie sich Ausloggen wollen?</p>
                        <p:commandButton action="#{userBean.logout()}" value="Ja" style="margin-right: 5%" immediate="true"/>
                        <p:commandButton action="#{langosCharlyService.toBase}" value="Nein" style="margin-left: 5%"/>
                        
                    </h:form>
                </div>
            </div>
        </div>

    </ui:define>
</ui:composition>

Langos Charly/web/unternehmen/meinUser.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template/template.xhtml"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <ui:define name="content">
        <div class="ui-g">
            <div class="ui-g-12">
                <div class="card">

                    <h1 class="lightBlack" style="text-align: center">Mein User</h1>

                    <h:form>


                        <p:growl id="growl" sticky="false" showDetail="true" life="10000" />


                        <p:outputLabel for="bild" value="Profilbild" style="display: none"/>
                        <p:fileUpload id="bild" mode="advanced" auto="true" sizeLimit="2000000" allowTypes="/(\.|\/)(jpe?g)$/" fileUploadListener="#{userBean.fileUpload}" style="width: 290px"/>

                        <br/>
                        
                        <p:selectOneRadio id="selectTyp" value="#{userBean.typ}">
                            <f:selectItems value="#{userBean.allTyps}" var="typ" itemLabel="#{typ.name}" itemValue="#{typ}"/>
                            <f:ajax execute="selectTyp" render="userGrid"/>
                        </p:selectOneRadio>

                        <br/>

                        <p:panelGrid id="userGrid" columns="2" styleClass="noBorders">

                            <c:choose id="choose">
                                <c:when test="#{userBean.firma}">
                                    <p:outputLabel for="firmenname" value="Firmenname "/>
                                    <p:inputText id="firmenname" value="#{userBean.firmenname}" maxlength="70" required="true" />
                                </c:when>
                                <c:otherwise>
                                    <c:choose>
                                        <c:when test="#{userBean.verein}">
                                            <p:outputLabel for="vereinsname" value="Vereinsname "/>
                                            <p:inputText id="vereinsname" value="#{userBean.firmenname}" maxlength="70" required="true"/>
                                        </c:when>
                                        <c:otherwise>
                                            <p:outputLabel for="privat" value="Privat "/>
                                            <p:inputText id="privat" value="Privatperson" disabled="true"/>
                                        </c:otherwise>
                                    </c:choose>
                                </c:otherwise>
                            </c:choose>




                            <p:outputLabel for="vorname" value="Vorname "/>
                            <p:inputText id="vorname" maxlength="30" value="#{userBean.vorname}" />

                            <p:outputLabel for="nachname" value="Nachname "/>
                            <p:inputText id="nachname" maxlength="30" value="#{userBean.nachname}" />

                            <p:outputLabel for="email" value="Email "/>
                            <p:inputText id="email" value="#{userBean.email}" required="true" />

                            <p:outputLabel for="telefonnummer" value="Telefonnummer "/>
                            <p:inputText id="telefonnummer" value="#{userBean.telefonnummer}"  />



                            <p:outputLabel for="adresse" value="Adresse "/>
                            <p:inputText id="adresse" value="#{userBean.adresse}" />

                            <p:outputLabel for="plz" value="Postleitzahl "/>
                            <p:inputText id="plz" value="#{userBean.plz}" />

                            <p:outputLabel for="ort" value="Ort "/>
                            <p:inputText id="ort" value="#{userBean.ort}" />

                            <p:commandButton value="Speichern" action="#{userBean.changeUser}" update="@all" icon="fa fa-save"/>

                        </p:panelGrid>

                        <br/>

                        <p:commandButton value="Passwort ändern" action="neuesPasswort.xhtml?faces-redirect=true" />

                    </h:form>

                </div>
            </div>
        </div>

    </ui:define>

</ui:composition>

Langos Charly/web/unternehmen/neuesPasswort.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template/template.xhtml"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <ui:define name="content">
        <div class="ui-g">
            <div class="ui-g-12">
                <div class="card">

                    <h:form>
                        
                        <p:defaultCommand target="submit" />
                        
                        <p:growl id="growl" sticky="false" showDetail="true" life="10000" />

                        <h1 class="lightBlack">Hier kannst du dein Passwort ändern</h1>

                        <p:panelGrid columns="2" columnClasses="column" styleClass="noBorders">
                            
                            <h:outputLabel for="passwortAlt" value="Altes Passwort"/>
                            <p:password id="passwortAlt" value="#{userBean.passwort}" required="true"/>  

                            <h:outputLabel for="Passwort1" value="Neues Passwort"/>
                            <p:password id="Passwort1" value="#{userBean.neuesPasswort}" match="Passwort2" label="Passwort1" required="true"/>  

                            <h:outputLabel for="Passwort2" value="Passwort bestätigen" />  
                            <p:password id="Passwort2" label="Password2" required="true"/>  

                            <p:commandButton value="Zurück" action="meinUser.xhtml?faces-redirect=true" immediate="true"/>

                            <p:commandButton id="submit" value="Passwort ändern" action="#{userBean.passwortAendern}" />

                        </p:panelGrid>

                    </h:form>

                </div>
            </div>
        </div>

    </ui:define>

</ui:composition>

Langos Charly/web/unternehmen/produktion.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template/template.xhtml">

    <ui:define name="content">
        <div class="ui-g">
            <div class="ui-g-12">
                <div class="card centerText">
                    <h1 class="lightBlack">Die Produktion</h1>
                    <p>
                    #{informationBean.getInformation(1)}    
                    </p>

                    <br/>
                    <br/>
                    <br/>

                    <p:panelGrid columns="2" style="width: 100%" styleClass="noBorders">

                        <p:graphicImage value="#{imageBean.image}" cache="false" style="width: 100%" rendered="#{imageBean.showImage(3)}">
                            <f:param name="bild" value="3" />
                        </p:graphicImage>

                        <p:graphicImage value="#{imageBean.image}" cache="false" style="width: 100%" rendered="#{imageBean.showImage(4)}">
                            <f:param name="bild" value="4" />
                        </p:graphicImage>



                    </p:panelGrid>
                </div>
            </div>
        </div>

    </ui:define>

</ui:composition>

Langos Charly/web/unternehmen/service.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template/template.xhtml">

    <ui:define name="content">
        <div class="ui-g">
            <div class="ui-g-12">
                <div class="card centerText">
                    <h1 class="lightBlack">Unser Service</h1>
                    <p>
                        #{informationBean.getInformation(2)}  
                    </p>

                    <br/>
                    <br/>
                    <br/>

                    <p:panelGrid columns="2" style="width: 100%" styleClass="noBorders">

                        <p:graphicImage value="#{imageBean.image}" cache="false" style="width: 100%" rendered="#{imageBean.showImage(5)}">
                            <f:param name="bild" value="5" />
                        </p:graphicImage>

                        <p:graphicImage value="#{imageBean.image}" cache="false" style="width: 100%" rendered="#{imageBean.showImage(6)}">
                            <f:param name="bild" value="6" />
                        </p:graphicImage>



                    </p:panelGrid>

                </div>
            </div>
        </div>

    </ui:define>

</ui:composition>

Langos Charly/web/unternehmen/ueberUns.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template/template.xhtml">

    <ui:define name="content">
        <div class="ui-g">
            <div class="ui-g-12">
                <div class="card centerText">           

                    <h:form>

                        <p:growl id="growl" sticky="false" showDetail="true" life="10000" />

                        <h1 class="lightBlack">Geschichte unserer Entstehung</h1>

                        <p class="lightBlack">

                            #{informationBean.getInformation(0)}   </p>

                        <br/>
                        <br/>
                        <br/>

                        <p:panelGrid columns="2" style="width: 100%" styleClass="noBorders">

                            <p:graphicImage value="#{imageBean.image}" cache="false" style="width: 100%" rendered="#{imageBean.showImage(1)}">
                                <f:param name="bild" value="1" />
                            </p:graphicImage>

                            <p:graphicImage value="#{imageBean.image}" cache="false" style="width: 100%" rendered="#{imageBean.showImage(2)}">
                                <f:param name="bild" value="2" />
                            </p:graphicImage>



                        </p:panelGrid>



                    </h:form>

                </div>
            </div>
        </div>

    </ui:define>

</ui:composition>