Langos Charly/src/java/at/htlpinkafeld/langoscharly/gui/MenuBean.java
package at.htlpinkafeld.langoscharly.gui;

import at.htlpinkafeld.langoscharly.pojo.User;
import at.htlpinkafeld.langoscharly.service.LangosCharlyService;
import javax.annotation.PostConstruct;

/**
 *
 * @author Kolar
 */
public class MenuBean implements BaseBean {

    private User user;
    private LangosCharlyService service;

    public MenuBean() {
    }

    @PostConstruct
    public void init() {
        user = service.getCurrentUser();
    }

    public boolean isGast() {
        return user.getFirmenname().equals(LangosCharlyService.GAST);
    }

    @Override
    public LangosCharlyService getLangosCharlyService() {
        return service;
    }

    @Override
    public void setLangosCharlyService(LangosCharlyService service) {
        this.service = service;
    }

    public boolean isBestellen() {

        if (user != null) {
            if (user.getRolle().isBestellen()) {
                return true;
            }
        }

        return false;

    }

    public boolean isKalender() {
        if (user != null) {
            if (user.getRolle().isKalender()) {
                return true;
            }
        }

        return false;
    }

    public boolean isStatistik() {
        if (user != null) {
            if (user.getRolle().isStatisik()) {
                return true;
            }
        }

        return false;
    }

    public boolean isLagerbestand() {
        if (user != null) {
            if (user.getRolle().isLagerbestand()) {
                return true;
            }
        }

        return false;
    }

    public boolean isAdmin() {
        if (user != null) {
            if (user.getRolle().isAdmin()) {
                return true;
            }
        }

        return false;
    }

    public boolean isBuchen() {
        if (user != null) {
            if (user.getRolle().isBuchen()) {
                return true;
            }
        }

        return false;
    }

    public boolean isSuperAdmin() {
        if (user != null) {
            if (user.getRolle().isSuperadmin()) {
                return true;
            }
        }

        return false;
    }

    public boolean isShowAdminArea() {
        if (user != null) {
            if (user.getRolle().isSuperadmin()) {
                return true;
            }
            if (user.getRolle().isStatisik()){
                return true;
            }
            if(user.getRolle().isAdmin()) {
                return true;
            }
        }

        return false;
    }
    
}

Langos Charly/src/java/at/htlpinkafeld/langoscharly/gui/UserBean.java
package at.htlpinkafeld.langoscharly.gui;

import at.htlpinkafeld.langoscharly.pojo.Rolle;
import at.htlpinkafeld.langoscharly.pojo.User;
import at.htlpinkafeld.langoscharly.pojo.enums.Typ;
import at.htlpinkafeld.langoscharly.service.LangosCharlyService;
import at.htlpinkafeld.langoscharly.utilities.MailClient;
import at.htlpinkafeld.langoscharly.utilities.PasswortEncryption;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.security.spec.InvalidKeySpecException;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.event.PhaseId;
import javax.imageio.ImageIO;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

/**
 *
 * @author Kolar
 */
public class UserBean implements BaseBean {

    private LangosCharlyService service;
    private InputStream bild;
    private int userID;
    private String firmenname;
    private Typ typ = Typ.FIRMA;
    private String vorname, nachname;
    private String email;
    private String passwort;
    private String telefonnummer;
    private String adresse;
    private int plz;
    private String ort;
    private Rolle rolle;
    private User changeUser;
    private int rollenID;
    private String neuesPasswort;

    private List<Rolle> rollen;
    private final String cookieUserID = "cUserID";
    private final String cookiePw = "cPw";
    private final int cookieDuration = 2628000; // 1 Monat
    private final String cookiePath = "/";
    private final boolean cookieHttpOnly = true;

    public UserBean() {
    }

    @PostConstruct
    public void init() {
        typ = Typ.FIRMA;

        new Thread(() -> {
            service.preLoad();
        }).start();
        
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = ((HttpServletRequest) (context.getExternalContext().getRequest()));
        HttpServletResponse response = ((HttpServletResponse) (context.getExternalContext().getResponse()));

        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        if (request.getParameter("JSESSIONID") != null) {
            Cookie userCookie = new Cookie("JSESSIONID", request.getParameter("JSESSIONID"));
            response.addCookie(userCookie);
        } else {
            String sessionId = session.getId();
            Cookie userCookie = new Cookie("JSESSIONID", sessionId);
            response.addCookie(userCookie);
        }

        
        Cookie[] cookiesArr = request.getCookies();
        if (cookiesArr != null && cookiesArr.length > 0) {
            for (Cookie cookie : cookiesArr) {
                String cName = cookie.getName();
                String cValue = cookie.getValue();

                if (cName.equals(cookieUserID)) {
                    userID = Integer.valueOf(cValue);
                } else if (cName.equals(cookiePw)) {
                    passwort = cValue;
                }
            }
        }
        if (userID > -1 && passwort != null && passwort.length() > 0) {

            try {

                setCookies(userID, passwort);

            } catch (Exception ex) {
            }

            try {
                passwort = passwort.replace("+", " ");
                login(this.service.getUser(userID), passwort);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(UserBean.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        } else {
            passwort = null;
            userID = -1;
        }
    }

    public boolean isFirma() {
        return typ.equals(Typ.FIRMA);
    }

    public boolean isVerein() {
        return typ.equals(Typ.VEREIN);
    }

    public String getNeuesPasswort() {
        return neuesPasswort;
    }

    public void setNeuesPasswort(String neuesPasswort) {
        this.neuesPasswort = neuesPasswort;
    }

    public LangosCharlyService getService() {
        return service;
    }

    public void setService(LangosCharlyService service) {
        this.service = service;
    }

    public void setUserID(int userID) {
        this.userID = userID;
    }

    public InputStream getBild() {
        return bild;
    }

    public void setBild(InputStream bild) {
        this.bild = bild;
    }

    public String getFirmenname() {
        return firmenname;
    }

    public void setFirmenname(String Firmenname) {
        this.firmenname = Firmenname;
    }

    public Typ getTyp() throws IOException {
        return typ;
    }

    public void setTyp(Typ typ) {
        this.typ = typ;
    }

    public String getVorname() {
        return vorname;
    }

    public void setVorname(String vorname) {
        this.vorname = vorname;
    }

    public String getNachname() {
        return nachname;
    }

    public void setNachname(String nachname) {
        this.nachname = nachname;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPasswort() {
        return passwort;
    }

    public void setPasswort(String passwort) {
        this.passwort = passwort;
    }

    public String getTelefonnummer() {
        return telefonnummer;
    }

    public void setTelefonnummer(String telefonnummer) {
        this.telefonnummer = telefonnummer;
    }

    public String getAdresse() {
        return adresse;
    }

    public void setAdresse(String Adresse) {
        this.adresse = Adresse;
    }

    public int getPlz() {
        return plz;
    }

    public void setPlz(int plz) {
        this.plz = plz;
    }

    public String getOrt() {
        return ort;
    }

    public void setOrt(String ort) {
        this.ort = ort;
    }

    public int getUserID() {
        return userID;
    }

    public Rolle getRolle() {
        return rolle;
    }

    public void setRollenID(int rollenID) {
        this.rollenID = rollenID;
    }

    public int getRollenID() {
        return rollenID;
    }

    public List<Rolle> getRollen() {
        rollen = service.getRollen();
        return rollen;
    }

    public String getName(User user) {
        return service.getName(user);
    }

    public String getName(int id) {
        return getName(this.service.getUser(id));
    }

    public StreamedContent getImage() throws IOException {
        FacesContext context = FacesContext.getCurrentInstance();

        if (context.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
            return new DefaultStreamedContent();
        } else {

            return new DefaultStreamedContent(this.service.getCurrentUser().getBild(), "image/jpeg");
        }
    }

    public User getCurrentUser() {
        return this.service.getCurrentUser();
    }

    public boolean isPrivat() {
        if (service.getCurrentUser() != null) {
            return service.getCurrentUser().getTyp().equals(Typ.PRIVAT);
        }
        return false;
    }

    public boolean isDefaultImage() {
        try {
            if (service.getCurrentUser().getBild() != null) {
                return false;
            }
        } catch (Exception ex) {
        }

        return true;
    }

    public void fileUpload(FileUploadEvent event) {
        try {
            bild = event.getFile().getInputstream();

            BufferedImage sourceImage = ImageIO.read(bild);
            Image thumbnail = sourceImage.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
            BufferedImage bufferedThumbnail = new BufferedImage(thumbnail.getWidth(null),
                    thumbnail.getHeight(null),
                    BufferedImage.TYPE_INT_RGB);
            bufferedThumbnail.getGraphics().drawImage(thumbnail, 0, 0, null);
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            ImageIO.write(bufferedThumbnail, "jpeg", baos);
            bild = new ByteArrayInputStream(baos.toByteArray());

            FacesContext context = FacesContext.getCurrentInstance();
            context.addMessage(null, new FacesMessage("Erfolgreich", "Bild wurde erfolgreich hochgeladen"));

            this.service.updateImage(this.service.getCurrentUser(), bild);

        } catch (IOException e) {
            Logger.getLogger(UserBean.class).fatal("Bild nicht möglich hochzuladen: " + e.getMessage(), e);
        }
    }

    public void changePassword() {
        User user = service.getCurrentUser();
        user.setPasswort(passwort);
        this.service.updateUser(user);
    }

    public String register() throws IOException {

        if (typ.equals(Typ.PRIVAT)) {
            firmenname = Typ.PRIVAT.getName();
        }

        byte[] salt = null;
        byte[] hashedPasswort = null;
        try {
            salt = PasswortEncryption.salt();
            hashedPasswort = PasswortEncryption.hash(passwort, salt);

        } catch (InvalidKeySpecException | NoSuchAlgorithmException ex) {
            Logger.getLogger(UserBean.class
            ).fatal("User konnte nicht erstellt werden");
            System.out.println(ex.toString());
            throw new RuntimeException("User konnte nicht erstellt werden");
        }

Langos Charly/web/WEB-INF/template/footer.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

    <div class="footer" style="align-content: center">

        <div class="ui-g">

            <div class="ui-g-12 ui-lg-2" style="text-align: center">
                <p:graphicImage id="footer-logo" name="images/logo.jpg" library="icarus-layout" style="height:100px" cache="true"/>
            </div>

            <div class="ui-g-12 ui-lg-8" style="text-align: center">
                <p>Langos Charly<br/>
                    Mail: <a href="MAILTO:office@langos-charly.at"> office@langos-charly.at</a><br/>
                    #{informationBean.getInformation(3)}</p>
            </div>


            <div class="ui-g-12 ui-lg-2" style="text-align: center">
                <p>© #{kalenderBean.currentYear} Langos Charly</p>
            </div>

        </div>
    </div>

</ui:composition>

Langos Charly/web/WEB-INF/template/layoutmenu.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pi="http://primefaces.org/icarus"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">


    <h:form id="menuform">

        <pi:menu widgetVar="IcarusMenu">

            <c:choose>
                <c:when test="#{menuBean.gast}">

                    <p:menuitem icon="fa fa-home" value="Über uns" outcome="/unternehmen/ueberUns.xhtml?faces-redirect=true"/>
                    <p:menuitem icon="fa fa-building-o" value="Die Produktion" outcome="/unternehmen/produktion.xhtml?faces-redirect=true" />
                    <p:menuitem icon="fa fa-shopping-basket" value="Unser Service" outcome="/unternehmen/service.xhtml?faces-redirect=true"/>
                    <c:choose>
                        <c:when test="#{menuBean.buchen}" >
                            <p:menuitem icon="fa fa-calendar-plus-o" value="Fest Buchen" outcome="/buchen/festBuchen.xhtml?faces-redirect=true"/>
                        </c:when>
                    </c:choose>

                </c:when>
                <c:otherwise>

                    <p:submenu icon="fa fa-home" label="Unternehmen">
                        <p:menuitem value="Über uns" outcome="/unternehmen/ueberUns.xhtml?faces-redirect=true"/>
                        <p:menuitem value="Die Produktion" outcome="/unternehmen/produktion.xhtml?faces-redirect=true" />
                        <p:menuitem value="Unser Service" outcome="/unternehmen/service.xhtml?faces-redirect=true"/>
                    </p:submenu>

                    <p:submenu icon="fa fa-shopping-basket" label="Dienstleistungen">
                        <p:menuitem value="Fest buchen" outcome="/buchen/festBuchen.xhtml?faces-redirect=true" rendered="#{menuBean.buchen}" />
                        <p:menuitem value="Langos bestellen" outcome="/bestellen/products.xhtml?faces-redirect=true" rendered="#{menuBean.bestellen}"/>
                        <p:menuitem value="Bestell Übersicht" outcome="/bestellen/bestellUebersicht.xhtml?faces-redirect=true" rendered="#{menuBean.bestellen}"/>
                    </p:submenu>

                    <p:menuitem icon="fa fa-calendar" value="Kalender" outcome="/kalender/kalender.xhtml?faces-redirect=true" rendered="#{menuBean.kalender}" />
                    <p:menuitem icon="fa fa-cubes" value="Lagerbestand" outcome="/lager/lagerbestand.xhtml?faces-redirect=true" rendered="#{menuBean.lagerbestand}"/>
                    <p:submenu icon="fa fa-gears" label="Adminbereich" rendered="#{menuBean.showAdminArea}" >
                        <p:menuitem value="Statistik" outcome="/statistik/statistik.xhtml?faces-redirect=true" rendered="#{menuBean.statistik}" />
                        <p:menuitem value="Users" outcome="/superadmin/users.xhtml?faces-redirect=true" rendered="#{menuBean.superAdmin}"  />
                        <p:menuitem value="Rollen" outcome="/superadmin/rollen.xhtml?faces-redirect=true" rendered="#{menuBean.superAdmin}" />
                        <p:menuitem value="Langos" outcome="/superadmin/langos.xhtml?faces-redirect=true" rendered="#{menuBean.superAdmin}" />
                        <p:menuitem value="Hauptspeisen" outcome="/superadmin/hauptspeisen.xhtml?faces-redirect=true" rendered="#{menuBean.superAdmin}" />
                        <p:menuitem value="Festverwaltung" outcome="/admin/festBuchenUebersicht.xhtml?faces-redirect=true" rendered="#{menuBean.admin}" />
                        <p:menuitem value="Bestellverwaltung" outcome="/admin/bestellVerwaltung.xhtml?faces-redirect=true" rendered="#{menuBean.admin}" />
                        <p:menuitem value="Bilder" outcome="/superadmin/bildBearbeiten.xhtml?faces-redirect=true" rendered="#{menuBean.superAdmin}" />
                        <p:menuitem value="Informationen Bearbeiten" outcome="/superadmin/informationenBearbeiten.xhtml?faces-redirect=true" rendered="#{menuBean.superAdmin}" />

                    </p:submenu>

                </c:otherwise>
            </c:choose>

        </pi:menu>

    </h:form>

</ui:composition>

Langos Charly/web/WEB-INF/template/sidebarheader.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">


    <div id="sidebar-header">
        <div id="logo-wrapper">
            <h:form>
                <h:commandLink action="#{langosCharlyService.getToBase}">
                    <div class="desktop">
                        <p:graphicImage name="images/LOGO.png" id="logo" library="icarus-layout" style="width: 70%; float: left; padding-left: 10%" cache="true"/>
                    </div>
                    <div class="mobil">
                        <p:graphicImage name="images/LOGO.png" id="logo2" library="icarus-layout" style="width: 150%; margin-top: 8px;" cache="true"/>
                    </div>
                </h:commandLink>
            </h:form>
        </div>
        <a id="slim-menu-button" href="#">
            <i class="fa fa-bars" aria-hidden="true"></i>
        </a>
    </div>


</ui:composition>

Langos Charly/web/WEB-INF/template/template.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <f:facet name="first">
            <meta http-equiv="X-UA-Compatible" content="IE=edge" />
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
            <meta name="apple-mobile-web-app-capable" content="yes" />
        </f:facet>
        <title>Langos Charly</title>
        <h:outputScript name="js/nanoscroller.js" library="icarus-layout" />
        <h:outputScript name="js/layout.js" library="icarus-layout" />

        <ui:insert name="head"/>

        <script type="text/javascript">
            window.CookieHinweis_options = {
                message: 'Diese Website nutzt Cookies, um bestmögliche Funktionalität bieten zu können.',
                agree: 'Ok, verstanden',
                learnMore: 'Mehr Infos',
                link: '/unternehmen/datenschutzerklaerung.xhtml', /* Link zu den eigenen Datenschutzbestimmungen */
                theme: 'dunkel-unten' /* weitere Theme-Optionen sind dunkel-oben oder hell-unten-rechts */
            };
        </script>
        <script type="text/javascript" src="https://s3.eu-central-1.amazonaws.com/website-tutor/cookiehinweis/script.js"/>
        
        <link rel="shortcut icon" href="http://localhost:8084/javax.faces.resource/images/icon.png.xhtml?ln=icarus-layout" type="image/x-icon"/>


    </h:head>

    <h:body style="background-image: url(/resources/icarus-layout/images/background.jpg); background-attachment: fixed">


        <div class="wrapper">

            <div id="sidebar-wrapper">
                <ui:include src="sidebarheader.xhtml" />

                <div class="sidebar-nav nano">
                    <div class="nano-content sidebar-scroll-content">
                        <ui:include src="layoutmenu.xhtml" />
                    </div>
                </div>
            </div>   

            <ui:include src="topbar.xhtml" />         

            <div id="main-wrapper">
                <div class="main-content">
                    <ui:insert name="content"></ui:insert>
                    <h:form id="errorForm">
                        <p:growl id="errorMessages" showDetail="true" life="7500">
                            <p:autoUpdate/>
                        </p:growl>
                    </h:form>
                </div>

                <ui:include src="footer.xhtml" />
            </div>
        </div>

        <p:ajaxStatus style="width:32px;height:32px;position:fixed;right:7px;bottom:7px">
            <f:facet name="start">
                <p:graphicImage name="images/preloader.gif" library="icarus-layout" style="width: 32px;"/>
            </f:facet>

            <f:facet name="complete">
                <h:outputText value="" />
            </f:facet>
        </p:ajaxStatus>

        <h:outputStylesheet name="css/animate.css" library="icarus-layout" />
        <h:outputStylesheet name="css/nanoscroller.css" library="icarus-layout" />
        <h:outputStylesheet name="css/layout-green.css" library="icarus-layout" />
    </h:body>

</html>

Langos Charly/web/WEB-INF/template/topbar.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
    xmlns:f="http://xmlns.jcp.org/jsf/core">

    <div id="top-bar-wrapper">
        <div id="top-bar">

            <c:choose>
                <c:when test="#{menuBean.gast}">

                    <div class="top-bar-profile">
                        <h:form>
                            <div class="desktop">
                                <p:commandButton value="Login" action="/login.xhtml?faces-redirect=true" style="margin-top: 5%; margin-bottom: 5%; margin-top: 15px; margin-right: 25%; width: 70%;"/>
                                <p:commandButton value="Registration" action="/registration.xhtml?faces-redirect=true" style="margin-bottom: 10%; margin-right: 20%; width: 80%;"/>
                            </div>
                            <div class="mobil" style="text-align: left">
                                <p:commandButton value="Login" action="/login.xhtml?faces-redirect=true" style="margin-top: 5%; margin-bottom: 5%; margin-right: 25%; width: 50%; background: #DB2A06 "/>
                                <p:commandButton value="Registration" action="/registration.xhtml?faces-redirect=true" style="margin-bottom: 10%; margin-right: 20%; width: 60%; background: #DB2A06"/>
                            </div>
                        </h:form>
                    </div>
                </c:when>
                <c:otherwise>

                    <div class="top-bar-profile">
                        <div class="profile-name">
                            <span> #{userBean.getName(userBean.currentUser)}</span> <br/>
                            <p:outputLabel value="#{userBean.currentUser.rolle.rolle}" />
                        </div>
                        <a href="#" id="profile-image">

                            <c:choose>
                                <c:when test="#{userBean.defaultImage}" >
                                    <p:graphicImage name="images/profile.png" library="icarus-layout" style="border: 0 none;" cache="false"/>
                                </c:when>
                                <c:otherwise>
                                    <p:graphicImage value="#{userBean.image}" cache="false" alt="[BILD]"/>
                                </c:otherwise>
                            </c:choose>

                        </a>
                        <h:form>
                            <div class="desktop">
                                <ul class="top-submenu animated flipInX" style="margin-left: -25px; width: 100%">
                                    <li>
                                        <a href="/unternehmen/meinUser.xhtml?faces-redirect=true">
                                            <i class="fa fa-fw fa-user"></i>
                                            <span>Mein Profil</span>
                                        </a>
                                    </li>
                                    <c:choose>
                                        <c:when test="#{menuBean.kalender}">
                                            <li>
                                                <a href="/kalender/kalender.xhtml?faces-redirect=true">
                                                    <i class="top-submenu-icon fa fa-fw fa-calendar"></i>
                                                    <span>Kalender</span>
                                                </a>
                                            </li>
                                        </c:when>
                                    </c:choose>
                                    <li>
                                        <a href="/unternehmen/logout.xhtml?faces-redirect=true">
                                            <i class="top-submenu-icon fa fa-fw fa-close"></i>
                                            <span>Ausloggen</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="mobil" style="text-align: left">
                                <ul class="top-submenu animated flipInX">
                                    <li>
                                        <a href="/unternehmen/meinUser.xhtml?faces-redirect=true">
                                            <i class="fa fa-fw fa-user"></i>
                                            <span>Mein Profil</span>
                                        </a>
                                    </li>
                                    <c:choose>
                                        <c:when test="#{menuBean.kalender}">
                                            <li>
                                                <a href="/kalender/kalender.xhtml?faces-redirect=true">
                                                    <i class="top-submenu-icon fa fa-fw fa-calendar"></i>
                                                    <span>Kalender</span>
                                                </a>
                                            </li>
                                        </c:when>
                                    </c:choose>
                                    <li>
                                        <a href="/unternehmen/logout.xhtml?faces-redirect=true">
                                            <i class="top-submenu-icon fa fa-fw fa-close"></i>
                                            <span>Ausloggen</span>
                                        </a>
                                    </li>
                                </ul>

                            </div>
                        </h:form>
                    </div>

                </c:otherwise>
            </c:choose>
        </div>
    </div>
</ui:composition>